name: Build

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build with Gradle
      run: ./gradlew assembleRelease
    
    - name: Create Installable ZIP
      run: |
        mkdir -p ./ZIP_INSTALL/system/priv-app/net.mfuertes.aagw.gateway
        cp ./app/build/outputs/apk/release/app-release-unsigned.apk ./ZIP_INSTALL/system/priv-app/net.mfuertes.aagw.gateway/base.apk
        cd ./ZIP_INSTALL && zip -r ../aawg_twrp.zip .

    - name: Upload the artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: aawg-release
        # Destination path
        path: |
          ./aawg_twrp.zip
          ./app/build/outputs/apk/release/app-release-unsigned.apk

